services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commafeed-backend
    ports:
      - "8082:8082"
    volumes:
      - commafeed-data:/commafeed/data
    restart: unless-stopped

volumes:
  commafeed-data:
